server:
  # 端口
  port: 7879
spring:
  application:
    name: spring-boot-demo
  profiles:
    active: sharding-sphere
  jackson:
    # 日期格式器 jackson格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 格林威冶标准时间 + 8 (北京时间)
    time-zone: GMT+8
#日志配置
logging:
  level:
    root: info
    com.example: debug
